name: Build and deploy

# run when a commit is pushed to "source" branch
on:
  push:
    branches:
    - source

jobs:
  buid:
    runs-on: ubuntu-20.04
    steps:
    # checkout to the commit that has been pushed
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    
    # install Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    
    - name: Clean public directory
      run: rm -rf public

    # build website
    - name: Build
      run: hugo --minify
      
    # push the generated content into the `main` (former `master`) branch.
    - name: Deploy
      id: deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: main # if your main branch is `master` use that here.
        publish_dir: ./public  

  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
        
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.SFTP_HOST }}
        port: ${{ secrets.SFTP_PORT }}
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASSWD }}
        localPath: './'
        remotePath: '/www'
